version: '3'
services:
    chat:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: MyChatRoomServer
        environment:
            - CHAT_PORT=8888
            - MAX_USERS=10
            - DB_HOST=db
            - DB_PORT=6379
        ports:
            - "8888:8888"
        restart: on-failure
    db:
        image: redis:latest
        container_name: MyChatRoomDB
        restart: on-failure