version: "3"
services:
  php:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/app
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=azerty
      - MYSQL_DATABASE=tp2
      - MYSQL_USER=tp2
      - MYSQL_PASSWORD=tp2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
volumes:
    dbdata: